Лаб. работа 1
SemenovKo/shmyaher pull request #3
Opened 2024-10-20 14:21 UTC by SemenovKo

Все получилось, вопросов нет

2024-10-22 22:04 UTC, rmushkin commented
Вопросов, быть может, и нет - но кода я тоже не вижу 😅 
Пожалуйста, загрузите, чтобы я мог проверить, прокомментировать и принять. Кроме того, дайте мне, пожалуйста, права на запись в репозиторий, чтобы я мог принять и закрыть пулл-реквест.

2024-10-23 09:43 UTC, SemenovKo commented
Извините, пока плохо разбираюсь в сайте.
Надеюсь, теперь все есть.

2024-10-23 17:55 UTC, rmushkin requested changes
Пожалуйста, исправьте пару мелочей и дайте мне доступ на запись в репозиторий, чтобы я мог принять и закрыть.

2024-10-23 17:55 UTC, rmushkin commented on Лаб. работа номер 1/task2.py
> +books_in_space = round(space/books)
[PEP8](https://peps.python.org/pep-0008/) (указания по стилю написания кода): нужны пробелы вокруг математических операторов

2024-10-23 17:55 UTC, rmushkin commented on Лаб. работа номер 1/task2.py
> +books_in_space = round(space/books)
Использование `round` тут опасно: можно округлить, грубо говоря, 99,9 до ста; но если на дискету влезает только 99 книг - то 100 не влезет!
Используйте приведение к целому. Оно просто отбрасывает дробную часть.

2024-10-23 17:55 UTC, rmushkin commented on Лаб. работа номер 1/task1.py
> +numbers [4] = sum(newnumbers)/len(numbers)
[PEP8](https://peps.python.org/pep-0008/) (указания по стилю написания кода): 
1. если имя переменной состоит из нескольких слов, их нужно разделять нижними подчёркиваниями (не `newnumbers`, а `new_numbers`)
2. Нужны пробелы вокруг математиечких операторов

2024-10-23 20:41 UTC, SemenovKo commented
Исправил!

2024-10-24 08:41 UTC, rmushkin requested changes
В одном месте затесался беглый пробел.
Кроме того, пожалуйста, удалите одну из папок - пусть на одну лабу будет одна.

2024-10-24 08:41 UTC, rmushkin commented on Лаб. работа номер 1/task1.py
> +numbers [4] = sum(new_numbers) / len(numbers)
Заметил ещё, что перед квадратной скобкой пробел не нужен.

2024-10-24 13:55 UTC, merged