Лаб. работа 2
SemenovKo/shmyaher pull request #6
Opened 2024-10-27 17:27 UTC by SemenovKo

Во втором задании фактически сумма - 18783 рубля 27... копеек, для того, чтобы округлить в большую сторону, добавляю функцию round и +1, ответ 18784 рубля
Но в пайчарме правильный ответ 18783...

2024-10-29 18:07 UTC, rmushkin requested changes
Есть микрозамечание насчёт округления, а так супер

2024-10-29 18:07 UTC, rmushkin commented on Лаб. работа 2/task1.py
Вообще тут нет ошибки. Поэтому принимается.
Однако у вас сломана семантика. Какой физический смысл имеет `budget`? Это баланс на конец месяца или начало следующего? Если я захочу вывести на экран количество оставшихся денег на конец всего нашего безбедного периода, что надо написать в `print(...)`?

2024-10-29 18:07 UTC, rmushkin commented on Лаб. работа 2/task2.py
> +for _ in range(months):
👍

2024-10-29 18:07 UTC, rmushkin commented on Лаб. работа 2/task2.py
> +print(f"Подушка безопасности, чтобы протянуть {months} месяцев без долгов:", round(money_capital + 1))
+1 это здорово, но ведь не всегда оно нужно. В половине случаев - нет...

2024-10-31 15:14 UTC, rmushkin requested changes
Не, `round` по-прежнему неправильно. Нужно округление в большую сторону. Его надо либо нагуглить, либо придумать - на вебинаре я про это сказал. :)

2024-10-31 16:59 UTC, SemenovKo commented on Лаб. работа 2/task1.py
Не очень ясно понял ваш вопрос. Скорее всего мой код считает так, будто увеличение цен происходит уже в первом месяце, хотя это не так. Я попробовал сделать без "budget", вроде бы все сошлось.

2024-11-01 19:08 UTC, rmushkin approved these changes
👍 ✅

2024-11-01 19:09 UTC, merged

2024-11-01 19:15 UTC, rmushkin commented on Лаб. работа 2/task1.py
Я прокомментирую чуть позже для всех. Тут нет, как я уже сказал, ошибки.